name: 'agritecture '
favicon: null
layout_spectrum: 0.8715689016971737
typography_spectrum: 0.345503504620865
title: AGRITECTURE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6c6a'
    - '#e2ecdd'
    - '#afb1b4'
    - '#323432'
    - '#8ea038'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
